services:
  web:
    build:
      context: .           # usamos el directorio actual
    container_name: django-app
    volumes:
      - .:/app             # mapeamos todo el proyecto a /app en el contenedor
    env_file:
      - .env.prod
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ./cloudflared:/etc/cloudflared

volumes:
  db_data: