version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: DB_LOL
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  web:
    build: .
    container_name: django_lec
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - app_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/etc/cloudflared
    restart: always
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge