# Generated by Django 5.2 on 2025-04-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Top', 'Top'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('ADC', 'ADC'), ('Support', 'Support')], max_length=10)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('veces_jugado', models.IntegerField(default=0)),
                ('veces_baneado', models.IntegerField(default=0)),
                ('winrate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoNeutral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Baron', 'Barón Nashor'), ('Dragon', 'Dragón'), ('Heraldo', 'Heraldo de la Grieta'), ('Torre', 'Torre'), ('Inhibidor', 'Inhibidor')], max_length=20)),
                ('minuto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('ano_fundacion', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaLEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Objetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitLEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporadaLEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('nombre', models.CharField(default='LEC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('objetivoneutral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.objetivoneutral')),
                ('subtipo', models.CharField(choices=[('Infernal', 'Infernal'), ('Oceano', 'Océano'), ('Nube', 'Nube'), ('Montaña', 'Montaña'), ('Hextech', 'Hextech'), ('Quimtech', 'Quimtech'), ('Anciano', 'Elder')], max_length=20)),
            ],
            bases=('database.objetivoneutral',),
        ),
        migrations.AddField(
            model_name='objetivoneutral',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.equipo'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_real', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('Top', 'Top'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('ADC', 'ADC'), ('Support', 'Support')], max_length=10)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='database.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorEnPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('oro', models.FloatField()),
                ('damage', models.FloatField()),
                ('vision', models.FloatField()),
                ('nivel', models.IntegerField()),
                ('damage_estructuras', models.FloatField()),
                ('campeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.campeon')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetosComprados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('orden_compra', models.IntegerField()),
                ('jugador_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_comprados', to='database.jugadorenpartido')),
                ('objeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.objetos')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion', models.DurationField()),
                ('numero_en_serie', models.IntegerField(default=1)),
                ('ladoequipo1', models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red')], max_length=10)),
                ('ladoequipo2', models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red')], max_length=10)),
                ('parche', models.CharField(blank=True, max_length=20, null=True)),
                ('kills_equipo1', models.IntegerField(default=0)),
                ('kills_equipo2', models.IntegerField(default=0)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo1', to='database.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo2', to='database.equipo')),
                ('ganador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='database.equipo')),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvps', to='database.jugador')),
                ('primera_sangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeras_sangres', to='database.jugador')),
                ('primera_torre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeras_torres', to='database.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='objetivoneutral',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.partido'),
        ),
        migrations.AddField(
            model_name='jugadorenpartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_en_partido', to='database.partido'),
        ),
        migrations.CreateModel(
            name='SeleccionCampeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pick', 'Pick'), ('Baneo', 'Baneo')], max_length=10)),
                ('orden', models.IntegerField()),
                ('lado', models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red')], max_length=10)),
                ('campeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.campeon')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='database.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BO1', 'BO1'), ('BO3', 'BO3'), ('BO5', 'BO5')], max_length=10)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_como_equipo1', to='database.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_como_equipo2', to='database.equipo')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_ganadas', to='database.equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='database.jornadalec')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='database.serie'),
        ),
        migrations.AddField(
            model_name='jornadalec',
            name='split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='database.splitlec'),
        ),
        migrations.AddField(
            model_name='splitlec',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='database.temporadalec'),
        ),
        migrations.CreateModel(
            name='ClasificacionLEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.equipo')),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='database.splitlec')),
            ],
            options={
                'ordering': ['-victorias'],
                'unique_together': {('equipo', 'split')},
            },
        ),
    ]
