# Generated by Django 5.2 on 2025-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
