# Generated by Django 5.2 on 2025-05-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugadorenpartida',
            unique_together={('jugador', 'partido', 'campeon')},
        ),
    ]
