# Generated by Django 5.2 on 2025-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_jugadorenpartida_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='playoffs',
            field=models.BooleanField(default=False),
        ),
    ]
