# Generated by Django 5.2 on 2025-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_serie_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='fecha',
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
