# Generated by Django 5.2 on 2025-05-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_partido_fecha_partido_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
