# Generated by Django 5.2 on 2025-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_serie_playoffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='seleccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
