# Generated by Django 5.2 on 2025-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_seleccion_seleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeon',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
