# Generated by Django 5.2 on 2025-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_jugador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
