# Generated by Django 5.2 on 2025-05-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_equipo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='equipo_azul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_azul', to='database.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='database.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_rojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_rojo', to='database.equipo'),
        ),
    ]
