# Generated by Django 5.2 on 2025-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_partido_equipo_azul_partido_equipo_ganador_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugadorenpartida',
            unique_together={('jugador', 'partido')},
        ),
        migrations.AddField(
            model_name='jugadorenpartida',
            name='damagetaken',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='damagetochampions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='jugadorenpartida',
            name='side',
        ),
    ]
