# Generated by Django 5.2 on 2025-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_jugadorenpartida_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='assistsat10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='assistsat15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='assistsat20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='assistsat25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='csat10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='csat15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='csat20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='csat25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='deathsat10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='deathsat15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='deathsat20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='deathsat25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='goldat10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='goldat15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='goldat20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='goldat25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='killsat10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='killsat15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='killsat20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='killsat25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='xpat10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='xpat15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='xpat20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='xpat25',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
