# Generated by Django 5.2 on 2025-05-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_jugadorenpartida_assistsat10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='campeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.campeon'),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.jugador'),
        ),
        migrations.AlterField(
            model_name='jugadorenpartida',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.partido'),
        ),
    ]
