# Generated by Django 5.2 on 2025-05-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_jugadorenpartida_campeon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seleccion',
            unique_together={('equipo', 'partido', 'campeon_seleccionado')},
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='campeon',
        ),
    ]
