# Generated by Django 5.2 on 2025-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_seleccion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivosneutralesmatados',
            name='firstbaron',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivosneutralesmatados',
            name='firstowerplate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivosneutralesmatados',
            name='firsttower',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
