# Generated by Django 5.2 on 2025-05-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_objetivosneutralesmatados_firstbaron_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivosneutralesmatados',
            name='firstbaron',
        ),
        migrations.RemoveField(
            model_name='objetivosneutralesmatados',
            name='firstdragon',
        ),
        migrations.RemoveField(
            model_name='objetivosneutralesmatados',
            name='firstowerplate',
        ),
        migrations.RemoveField(
            model_name='objetivosneutralesmatados',
            name='firsttower',
        ),
    ]
